### ISSUE TITLE
LDAP extension not loaded

### ISSUE THREAD

**Issue by vranki** [VSLCatena/ldap_login#19]
Hi, 

I've set up Piwigo with linuxserver/piwigo docker image and installed the ldap plugin on it successfully.
When saving the ldap settings with plugin admin, i'm getting the following errors on blank page.

Any ideas? Not sure if the bug is in the docker image or in the plugin. At least the error is not very user friendly. File class.ldap.php is owned by 1007:1007 which is also the UID/GID Piwigo has been set up to run as.

```
LDAP extension not loaded

Warning: file_put_contents(/var/log/ldap_login.log): failed to open stream: Permission denied in /config/www/gallery/plugins/Ldap_Login/class.ldap.php on line 13

Warning: file_put_contents(/var/log/ldap_login.log): failed to open stream: Permission denied in /config/www/gallery/plugins/Ldap_Login/class.ldap.php on line 13

Warning: file_put_contents(/var/log/ldap_login.log): failed to open stream: Permission denied in /config/www/gallery/plugins/Ldap_Login/class.ldap.php on line 13
LDAP extension not loaded

Fatal error: Uncaught Error: Call to undefined function ldap_err2str() in /config/www/gallery/plugins/Ldap_Login/class.ldap.php:135 Stack trace: #0 /config/www/gallery/plugins/Ldap_Login/class.ldap.php(30): Ldap->getErrorString() #1 /config/www/gallery/plugins/Ldap_Login/admin/configuration.php(59): Ldap->check_ldap() #2 /config/www/gallery/plugins/Ldap_Login/admin.php(20): include('/config/www/gal...') #3 /config/www/gallery/admin/plugin.php(68): include_once('/config/www/gal...') #4 /config/www/gallery/admin.php(312): include('/config/www/gal...') #5 {main} thrown in /config/www/gallery/plugins/Ldap_Login/class.ldap.php on line 135
```

**Comment by vranki** [comment]
Got it working by installing php-ldap on the server.
